In [6]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing, svm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from sklearn.manifold import LocallyLinearEmbedding
from sklearn.metrics import accuracy_score, confusion_matrix
import warnings
warnings.filterwarnings("ignore")


In [16]:
df=pd.read_csv("pca.csv")
df.drop(['trans_date_trans_time', 'trans_num', 'merch_lat', 'merch_long', 'dob'], axis=1, inplace=True)


In [18]:
categorical_cols= []
for col in df.columns:
    if(df[col].dtype=='object'):
        categorical_cols.append(col)
print(categorical_cols)


['merchant', 'category', 'city', 'state', 'job']


In [19]:
df=pd.get_dummies(df, columns=categorical_cols)
df.describe()


amt          lat         long      city_pop     is_fraud  \
count  1333.000000  1333.000000  1333.000000  1.333000e+03  1333.000000   
mean     69.162273    39.869987  -111.438044  9.601609e+04     0.006002   
std     125.879021     5.694163    13.698908  2.625325e+05     0.077266   
min       1.050000    20.027100  -165.672300  4.600000e+01     0.000000   
25%       9.860000    36.715400  -120.664900  4.670000e+02     0.000000   
50%      49.740000    39.741700  -111.794100  1.517000e+03     0.000000   
75%      84.430000    42.277000  -101.136000  3.488200e+04     0.000000   
max    3178.510000    65.689900   -89.628700  1.312922e+06     1.000000   

       merchant_"Adams, Kovacek and Kuhlman"  \
count                             1333.00000   
mean                                 0.00150   
std                                  0.03872   
min                                  0.00000   
25%                                  0.00000   
50%                                  0.00000   
75%                                  0.00000   
max                                  1.00000   

       merchant_"Altenwerth, Cartwright and Koss"  \
count                                  1333.00000   
mean                                      0.00075   
std                                       0.02739   
min                                       0.00000   
25%                                       0.00000   
50%                                       0.00000   
75%                                       0.00000   
max                                       1.00000   

       merchant_"Bahringer, Bergnaum and Quitzon"  \
count                                 1333.000000   
mean                                     0.003751   
std                                      0.061153   
min                                      0.000000   
25%                                      0.000000   
50%                                      0.000000   
75%                                      0.000000   
max                                      1.000000   

       merchant_"Bahringer, Schoen and Corkery"  \
count                               1333.000000   
mean                                   0.002251   
std                                    0.047404   
min                                    0.000000   
25%                                    0.000000   
50%                                    0.000000   
75%                                    0.000000   
max                                    1.000000   

       merchant_"Baumbach, Hodkiewicz and Walsh"  ...  job_Tax inspector  \
count                                1333.000000  ...        1333.000000   
mean                                    0.004501  ...           0.009752   
std                                     0.066964  ...           0.098309   
min                                     0.000000  ...           0.000000   
25%                                     0.000000  ...           0.000000   
50%                                     0.000000  ...           0.000000   
75%                                     0.000000  ...           0.000000   
max                                     1.000000  ...           1.000000   

       job_Telecommunications researcher  job_Television floor manager  \
count                        1333.000000                   1333.000000   
mean                            0.011253                      0.003751   
std                             0.105520                      0.061153   
min                             0.000000                      0.000000   
25%                             0.000000                      0.000000   
50%                             0.000000                      0.000000   
75%                             0.000000                      0.000000   
max                             1.000000                      1.000000   

       job_Television/film/video producer  \
count                         1333.000000   
mean                             0.003751   
std

In [20]:
X =df.drop(['is_fraud'], axis=1)
y =df['is_fraud']



In [23]:
std_scaler=StandardScaler()
scaled_df=std_scaler.fit_transform(X)


In [24]:
pca= PCA(n_components=20)
pca_df=pd.DataFrame(pca.fit_transform(scaled_df))

X_train, X_test, y_train, y_test=train_test_split(pca_df, y, test_size=0.33, random_state=42)


In [25]:
logreg=LogisticRegression(random_state=0)
logreg.fit(X_train, y_train)
Y_pred=logreg.predict(X_test) 
print("PCA accuracy : ", accuracy_score(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred))


PCA accuracy :  0.9886363636363636
[[435   1]
 [  4   0]]


In [26]:
tsne= TSNE(n_components=2, random_state=42)
tsne_df  =tsne.fit_transform(X)

X_train, X_test, y_train, y_test=train_test_split(tsne_df, y, test_size=0.33, random_state=42)

logreg=LogisticRegression(random_state=0)
logreg.fit(X_train, y_train)
Y_pred=logreg.predict(X_test) 
print("\nTSNE accuracy : ", accuracy_score(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred))



TSNE accuracy :  0.990909090909091
[[436   0]
 [  4   0]]


In [27]:
lle=LocallyLinearEmbedding(n_components=20, n_neighbors=100)
lle_df=lle.fit_transform(X)

X_train, X_test, y_train, y_test=train_test_split(lle_df, y, test_size=0.33, random_state=42)

logreg=LogisticRegression(random_state=0)
logreg.fit(X_train, y_train)
Y_pred=logreg.predict(X_test) 
print("\nLLE accuracy : ", accuracy_score(y_test, Y_pred))
print(confusion_matrix(y_test, Y_pred))



LLE accuracy :  0.990909090909091
[[436   0]
 [  4   0]]
